### ISSUE TITLE
Support networking.k8s.io ingresses

### ISSUE THREAD

**Issue by Aluxima** [uswitch/yggdrasil#53]
Kubernetes `extensions/v1beta1` Ingress will be removed in 1.22.  

In order to support all Kubernetes versions, Yggdrasil could try working with `networking.k8s.io` ingresses first before falling back to `extensions/v1beta1` if the cluster doesn't have the new API capability.

Any thoughts on other ways to handle both versions?

**Comment by Joseph-Irving** [comment]
Doing some kind of fallback is one way, but this could get a bit messy if your clusters are on different versions. It might be easier just to change it to networking.k8s and mark the min kubernetes version as 1.19, anything older than that is officially unsupported now anyway.

**Comment by Aluxima** [comment]
Yeah it will be cleaner to completely switch to `networking.k8s`.  
However we still have some old k8s cluster not supporting this apiversion yet, so we will have to wait until we upgrade.
